name: Repo Sync

on:
  workflow_dispatch:
    
permissions:
  contents: write
  pull-requests: write
  
env:
  GH_TOKEN: ${{ secrets.PR_TOKEN }}

jobs:
  repo-sync:
    name: Checkout repo and verify commits
    if: ${{ github.repository == 'theletterf/test-private' || github.repository == 'theletterf/testprivateb' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: theletterf/test-private
        source_branch: main
        destination_branch: repo-sync
        github_token: ${{ secrets.MY_TOKEN }}
    - name: Check if branch is ahead of main
      run: |
        if ! git merge-base --is-ancestor origin/main ${{ github.event.pull_request.head.sha }};
        then echo "This branch is not up to date with main";
        exit 1; fi

  create-pr:
    name: Create pull request
    needs: repo-sync
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR already exists
      id: check
      run: |
        prs=$(gh pr list \
          --repo "$GITHUB_REPOSITORY" \
          --json baseRefName,headRefName \
          --jq '
              map(select(.baseRefName == "main" and .headRefName == "repo-sync"))
              | length
          ')
        if ((prs > 0)); then
          echo "skip=true" >> "$GITHUB_OUTPUT"
        fi
    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
         script: |
           const { repo, owner } = context.repo;
           const result = await github.rest.pulls.create({
             title: 'Pulling ${{ github.ref }} into main',
             owner,
             repo,
             head: 'repo-sync',
             base: 'main',
             body: [
               'This PR is auto-generated by',
               '[actions/github-script](https://github.com/actions/github-script).'
             ].join('\n')
           });
           github.rest.issues.addLabels({
            owner,
            repo,
            issue_number: result.data.number,
            labels: ['sync', 'automated']
           });
