name: Repo Sync

on:
  workflow_dispatch:
  schedule: 
    - cron: "*/5 * * * *"
    
permissions:
  contents: write
  pull-requests: write
  
env:
  GH_TOKEN: ${{ secrets.PR_TOKEN }}

jobs:
  repo-sync:
    name: Synchronize repositories
    if: ${{ github.repository == 'theletterf/testprivate' || github.repository == 'theletterf/testprivateb' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: ${{ secrets.SOURCE_REPO }}
        source_branch: main
        destination_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        github_token: ${{ secrets.MY_TOKEN }}
    - name: Create pull request
      run: |
        gh pr create -l "sync" -B main --title "Pulling ${{ github.ref }} into main" -H ${{ secrets.INTERMEDIATE_BRANCH }} -b "This PR synchronizes the public and private docs repo." || gh pr edit -B main
